### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by GalGreenfield** [iseahound/Environment.ahk#1]
Hi,

I'm a new AutoHotkey user. How am I suppoed to use this script (for v1)?
I'm trying to write a script that users one of `Environment (for v1).ahk`'s functions but not sure what is required to expose that function to my script.

I tried running `Environment (for v1).ahk` both regularly and as an administrator, and to `include` it in my script file and none of these options worked - I get an error that either the file can't be included when I include it, and an error that the function isn't recognized when I don't import it (and just run my script - where I call it).

**Comment by iseahound** [comment]
1. Rename Environment (for v1).ahk to Environment.ahk. 
2. In the same directory create a new script.

```
#include Environment.ahk
MsgBox % userpath := Env_UserRead("PATH")
```

**Comment by GalGreenfield** [comment]
Hey, thanks for the quick reply!
Why in step 2 do you instruct me to create a script in the same directory - is there some kind of limitation on the path? Ideally I'd like to use a relative path.

**Comment by iseahound** [comment]
Then you would modify the include statement to be a relative path

**Comment by GalGreenfield** [comment]
> Then you would modify the include statement to be a relative path

Sorry, it was already a relative path. In any case, it doesn't work. Only an absolute path is working for me.

**Comment by GalGreenfield** [comment]
As I mentioned above, I was able to `include` your script for AHK v1, but am now getting this error:

```Error at line 31 in #include file "<path-to-the-v1-script-file".

Line Text: Env_UserAdd(name, value, type := "", location := "")
Error: Parameter of hotkey function must be optional.

The program will now exit.
```

I _assume_ that it couldn't find my environment variable?

**Comment by iseahound** [comment]
I suggest you ask on the forums or discord. In any case, I will update the readme with the instructions I have provided you for the benefit of future users.

https://www.autohotkey.com/boards/
https://www.autohotkey.com/docs/commands/_Include.htm
